// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blobAgent.proto

package blob

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DispatchResult_ResultCode int32

const (
	DispatchResult_SUCCESS                 DispatchResult_ResultCode = 0
	DispatchResult_UNKNOWN_ERROR           DispatchResult_ResultCode = 1
	DispatchResult_RATE_LIMIT_ERROR        DispatchResult_ResultCode = 2
	DispatchResult_MAX_SIZE_EXCEEDED_ERROR DispatchResult_ResultCode = 3
)

var DispatchResult_ResultCode_name = map[int32]string{
	0: "SUCCESS",
	1: "UNKNOWN_ERROR",
	2: "RATE_LIMIT_ERROR",
	3: "MAX_SIZE_EXCEEDED_ERROR",
}

var DispatchResult_ResultCode_value = map[string]int32{
	"SUCCESS":                 0,
	"UNKNOWN_ERROR":           1,
	"RATE_LIMIT_ERROR":        2,
	"MAX_SIZE_EXCEEDED_ERROR": 3,
}

func (x DispatchResult_ResultCode) String() string {
	return proto.EnumName(DispatchResult_ResultCode_name, int32(x))
}

func (DispatchResult_ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e2c29b867cc379f, []int{0, 0}
}

type BlobReadResponse_ResultCode int32

const (
	BlobReadResponse_SUCCESS       BlobReadResponse_ResultCode = 0
	BlobReadResponse_UNKNOWN_ERROR BlobReadResponse_ResultCode = 1
)

var BlobReadResponse_ResultCode_name = map[int32]string{
	0: "SUCCESS",
	1: "UNKNOWN_ERROR",
}

var BlobReadResponse_ResultCode_value = map[string]int32{
	"SUCCESS":       0,
	"UNKNOWN_ERROR": 1,
}

func (x BlobReadResponse_ResultCode) String() string {
	return proto.EnumName(BlobReadResponse_ResultCode_name, int32(x))
}

func (BlobReadResponse_ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e2c29b867cc379f, []int{1, 0}
}

type DispatchResult struct {
	Code                 DispatchResult_ResultCode `protobuf:"varint,1,opt,name=code,proto3,enum=DispatchResult_ResultCode" json:"code,omitempty"`
	ErrorMessage         string                    `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DispatchResult) Reset()         { *m = DispatchResult{} }
func (m *DispatchResult) String() string { return proto.CompactTextString(m) }
func (*DispatchResult) ProtoMessage()    {}
func (*DispatchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2c29b867cc379f, []int{0}
}

func (m *DispatchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DispatchResult.Unmarshal(m, b)
}
func (m *DispatchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DispatchResult.Marshal(b, m, deterministic)
}
func (m *DispatchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchResult.Merge(m, src)
}
func (m *DispatchResult) XXX_Size() int {
	return xxx_messageInfo_DispatchResult.Size(m)
}
func (m *DispatchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchResult.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchResult proto.InternalMessageInfo

func (m *DispatchResult) GetCode() DispatchResult_ResultCode {
	if m != nil {
		return m.Code
	}
	return DispatchResult_SUCCESS
}

func (m *DispatchResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type BlobReadResponse struct {
	Blob                 *Blob                       `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	Code                 BlobReadResponse_ResultCode `protobuf:"varint,2,opt,name=code,proto3,enum=BlobReadResponse_ResultCode" json:"code,omitempty"`
	ErrorMessage         string                      `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BlobReadResponse) Reset()         { *m = BlobReadResponse{} }
func (m *BlobReadResponse) String() string { return proto.CompactTextString(m) }
func (*BlobReadResponse) ProtoMessage()    {}
func (*BlobReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2c29b867cc379f, []int{1}
}

func (m *BlobReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobReadResponse.Unmarshal(m, b)
}
func (m *BlobReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobReadResponse.Marshal(b, m, deterministic)
}
func (m *BlobReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobReadResponse.Merge(m, src)
}
func (m *BlobReadResponse) XXX_Size() int {
	return xxx_messageInfo_BlobReadResponse.Size(m)
}
func (m *BlobReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlobReadResponse proto.InternalMessageInfo

func (m *BlobReadResponse) GetBlob() *Blob {
	if m != nil {
		return m.Blob
	}
	return nil
}

func (m *BlobReadResponse) GetCode() BlobReadResponse_ResultCode {
	if m != nil {
		return m.Code
	}
	return BlobReadResponse_SUCCESS
}

func (m *BlobReadResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type FormattedBlobReadResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormattedBlobReadResponse) Reset()         { *m = FormattedBlobReadResponse{} }
func (m *FormattedBlobReadResponse) String() string { return proto.CompactTextString(m) }
func (*FormattedBlobReadResponse) ProtoMessage()    {}
func (*FormattedBlobReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2c29b867cc379f, []int{2}
}

func (m *FormattedBlobReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormattedBlobReadResponse.Unmarshal(m, b)
}
func (m *FormattedBlobReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormattedBlobReadResponse.Marshal(b, m, deterministic)
}
func (m *FormattedBlobReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormattedBlobReadResponse.Merge(m, src)
}
func (m *FormattedBlobReadResponse) XXX_Size() int {
	return xxx_messageInfo_FormattedBlobReadResponse.Size(m)
}
func (m *FormattedBlobReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FormattedBlobReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FormattedBlobReadResponse proto.InternalMessageInfo

func (m *FormattedBlobReadResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type BlobSearch struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobSearch) Reset()         { *m = BlobSearch{} }
func (m *BlobSearch) String() string { return proto.CompactTextString(m) }
func (*BlobSearch) ProtoMessage()    {}
func (*BlobSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2c29b867cc379f, []int{3}
}

func (m *BlobSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobSearch.Unmarshal(m, b)
}
func (m *BlobSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobSearch.Marshal(b, m, deterministic)
}
func (m *BlobSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobSearch.Merge(m, src)
}
func (m *BlobSearch) XXX_Size() int {
	return xxx_messageInfo_BlobSearch.Size(m)
}
func (m *BlobSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobSearch.DiscardUnknown(m)
}

var xxx_messageInfo_BlobSearch proto.InternalMessageInfo

func (m *BlobSearch) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterEnum("DispatchResult_ResultCode", DispatchResult_ResultCode_name, DispatchResult_ResultCode_value)
	proto.RegisterEnum("BlobReadResponse_ResultCode", BlobReadResponse_ResultCode_name, BlobReadResponse_ResultCode_value)
	proto.RegisterType((*DispatchResult)(nil), "DispatchResult")
	proto.RegisterType((*BlobReadResponse)(nil), "BlobReadResponse")
	proto.RegisterType((*FormattedBlobReadResponse)(nil), "FormattedBlobReadResponse")
	proto.RegisterType((*BlobSearch)(nil), "BlobSearch")
}

func init() { proto.RegisterFile("blobAgent.proto", fileDescriptor_7e2c29b867cc379f) }

var fileDescriptor_7e2c29b867cc379f = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x4d, 0x5b, 0xff, 0xf4, 0xd4, 0xdd, 0x4d, 0x07, 0x61, 0x77, 0xe3, 0x22, 0x4b, 0x04,
	0xe9, 0x85, 0x4c, 0xb4, 0x3e, 0x41, 0xff, 0x44, 0x28, 0xda, 0xae, 0x4c, 0xba, 0xb8, 0xec, 0x4d,
	0x98, 0x24, 0x87, 0x34, 0xb4, 0xcd, 0x84, 0x99, 0xd1, 0x5a, 0xc4, 0x1b, 0x5f, 0xc1, 0xe7, 0xf0,
	0xc6, 0x87, 0xf0, 0x05, 0x7c, 0x05, 0x1f, 0x44, 0x32, 0x89, 0x2c, 0xbb, 0x55, 0xd0, 0xab, 0x39,
	0x7c, 0xe7, 0x3b, 0xc3, 0xfc, 0xe6, 0x3b, 0x70, 0x10, 0xad, 0x44, 0x34, 0x48, 0x31, 0xd7, 0xb4,
	0x90, 0x42, 0x0b, 0x07, 0x4a, 0xa1, 0xae, 0x4f, 0x52, 0x21, 0xd2, 0x15, 0x7a, 0xbc, 0xc8, 0x3c,
	0x9e, 0xe7, 0x42, 0x73, 0x9d, 0x89, 0x5c, 0x55, 0x5d, 0xf7, 0xbb, 0x05, 0xfb, 0xe3, 0x4c, 0x15,
	0x5c, 0xc7, 0x0b, 0x86, 0xea, 0xdd, 0x4a, 0x13, 0x0a, 0xad, 0x58, 0x24, 0x78, 0x64, 0x9d, 0x5a,
	0xbd, 0xfd, 0xbe, 0x43, 0xaf, 0xb7, 0x69, 0x75, 0x8c, 0x44, 0x82, 0xcc, 0xf8, 0xc8, 0x63, 0xd8,
	0x43, 0x29, 0x85, 0x0c, 0xd7, 0xa8, 0x14, 0x4f, 0xf1, 0xa8, 0x71, 0x6a, 0xf5, 0xda, 0xec, 0xbe,
	0x11, 0xa7, 0x95, 0xe6, 0x86, 0x00, 0x57, 0x83, 0xa4, 0x03, 0x77, 0x83, 0xf3, 0xd1, 0xc8, 0x0f,
	0x02, 0xfb, 0x16, 0xe9, 0xc2, 0xde, 0xf9, 0xec, 0xd5, 0xec, 0xec, 0xed, 0x2c, 0xf4, 0x19, 0x3b,
	0x63, 0xb6, 0x45, 0x1e, 0x80, 0xcd, 0x06, 0x73, 0x3f, 0x7c, 0x3d, 0x99, 0x4e, 0xe6, 0xb5, 0xda,
	0x20, 0x0f, 0xe1, 0x70, 0x3a, 0xb8, 0x08, 0x83, 0xc9, 0xa5, 0x1f, 0xfa, 0x17, 0x23, 0xdf, 0x1f,
	0xfb, 0xe3, 0xba, 0xd9, 0x74, 0xbf, 0x59, 0x60, 0x0f, 0x57, 0x22, 0x62, 0xc8, 0x13, 0x86, 0xaa,
	0x10, 0xb9, 0x42, 0x72, 0x0c, 0xad, 0xf2, 0x27, 0x0c, 0x4a, 0xa7, 0x7f, 0x9b, 0x1a, 0x83, 0x91,
	0xc8, 0xb3, 0x9a, 0xb2, 0x61, 0x28, 0x4f, 0xe8, 0xcd, 0xd9, 0x7f, 0xe0, 0x6c, 0xfe, 0x81, 0xf3,
	0xe9, 0xff, 0x70, 0xba, 0x1e, 0x1c, 0xbf, 0x14, 0x72, 0xcd, 0xb5, 0xc6, 0x64, 0xe7, 0xf1, 0x04,
	0x5a, 0x09, 0xd7, 0xdc, 0x3c, 0xbe, 0xcd, 0x4c, 0xed, 0x3e, 0x02, 0x28, 0x7d, 0x01, 0x72, 0x19,
	0x2f, 0x88, 0x0d, 0xcd, 0x25, 0x6e, 0x6b, 0x43, 0x59, 0xf6, 0xbf, 0x5a, 0xd0, 0x1e, 0xfe, 0x5e,
	0x06, 0xe2, 0xc2, 0xbd, 0xa4, 0x0e, 0x8f, 0x54, 0xf0, 0xce, 0xc1, 0x8d, 0x38, 0xc9, 0x13, 0x68,
	0x49, 0xe4, 0x09, 0xe9, 0xd0, 0xab, 0x8b, 0x9d, 0xee, 0xce, 0x77, 0x90, 0x39, 0xd8, 0xa5, 0xcf,
	0x5c, 0xae, 0x02, 0x2d, 0xb3, 0x3c, 0xbd, 0x3e, 0xe3, 0xd0, 0xbf, 0xa2, 0xb8, 0x87, 0x9f, 0x7f,
	0xfc, 0xfc, 0xd2, 0xe8, 0x92, 0xb6, 0xf7, 0xfe, 0xb9, 0xf7, 0x71, 0x89, 0xdb, 0x4f, 0x91, 0xe1,
	0x19, 0xf6, 0xa1, 0x17, 0x8b, 0x35, 0xc5, 0x0f, 0x05, 0x26, 0x19, 0xa7, 0x9b, 0xcd, 0x86, 0x2e,
	0xf8, 0x56, 0x69, 0x1e, 0x2f, 0x29, 0x37, 0x0b, 0x5d, 0x86, 0xa5, 0x28, 0x2f, 0xb2, 0x37, 0xd6,
	0xa5, 0x49, 0x2e, 0xba, 0x63, 0x36, 0xf7, 0xc5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0xce,
	0xc5, 0xad, 0xf6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlobAgentClient is the client API for BlobAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlobAgentClient interface {
	Dispatch(ctx context.Context, in *Blob, opts ...grpc.CallOption) (*DispatchResult, error)
	Read(ctx context.Context, in *BlobSearch, opts ...grpc.CallOption) (*BlobReadResponse, error)
	ReadBlobAsString(ctx context.Context, in *BlobSearch, opts ...grpc.CallOption) (*FormattedBlobReadResponse, error)
}

type blobAgentClient struct {
	cc *grpc.ClientConn
}

func NewBlobAgentClient(cc *grpc.ClientConn) BlobAgentClient {
	return &blobAgentClient{cc}
}

func (c *blobAgentClient) Dispatch(ctx context.Context, in *Blob, opts ...grpc.CallOption) (*DispatchResult, error) {
	out := new(DispatchResult)
	err := c.cc.Invoke(ctx, "/BlobAgent/dispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobAgentClient) Read(ctx context.Context, in *BlobSearch, opts ...grpc.CallOption) (*BlobReadResponse, error) {
	out := new(BlobReadResponse)
	err := c.cc.Invoke(ctx, "/BlobAgent/read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobAgentClient) ReadBlobAsString(ctx context.Context, in *BlobSearch, opts ...grpc.CallOption) (*FormattedBlobReadResponse, error) {
	out := new(FormattedBlobReadResponse)
	err := c.cc.Invoke(ctx, "/BlobAgent/readBlobAsString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobAgentServer is the server API for BlobAgent service.
type BlobAgentServer interface {
	Dispatch(context.Context, *Blob) (*DispatchResult, error)
	Read(context.Context, *BlobSearch) (*BlobReadResponse, error)
	ReadBlobAsString(context.Context, *BlobSearch) (*FormattedBlobReadResponse, error)
}

// UnimplementedBlobAgentServer can be embedded to have forward compatible implementations.
type UnimplementedBlobAgentServer struct {
}

func (*UnimplementedBlobAgentServer) Dispatch(ctx context.Context, req *Blob) (*DispatchResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (*UnimplementedBlobAgentServer) Read(ctx context.Context, req *BlobSearch) (*BlobReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedBlobAgentServer) ReadBlobAsString(ctx context.Context, req *BlobSearch) (*FormattedBlobReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBlobAsString not implemented")
}

func RegisterBlobAgentServer(s *grpc.Server, srv BlobAgentServer) {
	s.RegisterService(&_BlobAgent_serviceDesc, srv)
}

func _BlobAgent_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobAgentServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlobAgent/Dispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobAgentServer).Dispatch(ctx, req.(*Blob))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobAgent_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobAgentServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlobAgent/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobAgentServer).Read(ctx, req.(*BlobSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobAgent_ReadBlobAsString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobAgentServer).ReadBlobAsString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlobAgent/ReadBlobAsString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobAgentServer).ReadBlobAsString(ctx, req.(*BlobSearch))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlobAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BlobAgent",
	HandlerType: (*BlobAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "dispatch",
			Handler:    _BlobAgent_Dispatch_Handler,
		},
		{
			MethodName: "read",
			Handler:    _BlobAgent_Read_Handler,
		},
		{
			MethodName: "readBlobAsString",
			Handler:    _BlobAgent_ReadBlobAsString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blobAgent.proto",
}
