// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: blobAgent.proto

/*
Package blob is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package blob

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_BlobAgent_ReadBlobAsString_0(ctx context.Context, marshaler runtime.Marshaler, client BlobAgentClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BlobSearch
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["key"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "key")
	}

	protoReq.Key, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "key", err)
	}

	msg, err := client.ReadBlobAsString(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

// RegisterBlobAgentHandlerFromEndpoint is same as RegisterBlobAgentHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterBlobAgentHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterBlobAgentHandler(ctx, mux, conn)
}

// RegisterBlobAgentHandler registers the http handlers for service BlobAgent to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterBlobAgentHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterBlobAgentHandlerClient(ctx, mux, NewBlobAgentClient(conn))
}

// RegisterBlobAgentHandlerClient registers the http handlers for service BlobAgent
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "BlobAgentClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "BlobAgentClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "BlobAgentClient" to call the correct interceptors.
func RegisterBlobAgentHandlerClient(ctx context.Context, mux *runtime.ServeMux, client BlobAgentClient) error {

	mux.Handle("GET", pattern_BlobAgent_ReadBlobAsString_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_BlobAgent_ReadBlobAsString_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_BlobAgent_ReadBlobAsString_0(ctx, mux, outboundMarshaler, w, req, response_BlobAgent_ReadBlobAsString_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

type response_BlobAgent_ReadBlobAsString_0 struct {
	proto.Message
}

func (m response_BlobAgent_ReadBlobAsString_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*FormattedBlobReadResponse)
	return response.Data
}

var (
	pattern_BlobAgent_ReadBlobAsString_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 1, 0, 4, 1, 5, 1}, []string{"getBlob", "key"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_BlobAgent_ReadBlobAsString_0 = runtime.ForwardResponseMessage
)
