// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blob.proto

package blob

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Blob represents the data thats needs to be saved for a specific service call.
type Blob struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Content              []byte            `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_6903d1e8a20272e8, []int{0}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Blob) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Blob) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Blob)(nil), "Blob")
	proto.RegisterMapType((map[string]string)(nil), "Blob.MetadataEntry")
}

func init() { proto.RegisterFile("blob.proto", fileDescriptor_6903d1e8a20272e8) }

var fileDescriptor_6903d1e8a20272e8 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xc9, 0x4f,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x5a, 0xc0, 0xc8, 0xc5, 0xe2, 0x94, 0x93, 0x9f, 0x24,
	0x24, 0xc0, 0xc5, 0x9c, 0x9d, 0x5a, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x0a,
	0xe9, 0x73, 0x71, 0xe4, 0xa6, 0x96, 0x24, 0xa6, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x29, 0x30, 0x6b,
	0x70, 0x1b, 0x09, 0xeb, 0x81, 0x94, 0xea, 0xf9, 0x42, 0x45, 0x5d, 0xf3, 0x4a, 0x8a, 0x2a, 0x83,
	0xe0, 0x8a, 0x84, 0x24, 0xb8, 0xd8, 0x93, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x98, 0x15,
	0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x29, 0x6b, 0x2e, 0x5e, 0x14, 0x4d, 0x58, 0x6c, 0x13, 0xe1,
	0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c,
	0x4e, 0xaa, 0x5c, 0xd2, 0xc9, 0xf9, 0xb9, 0x7a, 0xa9, 0x15, 0x05, 0xa9, 0x29, 0x99, 0x89, 0x7a,
	0xe5, 0xe5, 0xe5, 0x7a, 0x20, 0x0f, 0x14, 0xeb, 0xe5, 0xe6, 0xa7, 0xa4, 0xe6, 0x04, 0x30, 0x46,
	0xb1, 0x80, 0xb8, 0x49, 0x6c, 0x60, 0x0f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x69,
	0x38, 0xb2, 0xde, 0x00, 0x00, 0x00,
}
